# Generated by Django 5.2.4 on 2025-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
